remove all unnecesary attempt to create new smart wallet since there is no self destruct
Revest-Finance/veFXS-FNFT pull request #3
Opened 2024-07-04 15:29 UTC by thanhtrinh2003

2024-07-09 12:41 UTC, nikollamalic requested changes

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
>      address public ADMIN_WALLET;
This should be immutable

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
>      constructor(address _provider, address _vE, address _distributor, address _revestAdmin) {
Make sure address zero can not be passed as any of these

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +    // Lock tokens
Use proper natspec.
Example:
```solidity
/**
  * @notice Transfers user tokens and locks them into....
  * @param endTime When the tokens will unlock..
 */
```

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +    function handleAdditionalDeposit(uint256 fnftId, uint256 amountToDeposit, uint256, address caller)
Use proper natspec. There is no value in adding a comment that repeats the method name

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +        address smartWallet = Clones.predictDeterministicAddress(TEMPLATE, keccak256(abi.encode(TOKEN, fnftId)));
This should be moved to a helper function. Example:
```solidity
    function _getWallets(uint256 fnftId) private view returns (address smartWallet, VestedEscrowSmartWallet wallet) {
        smartWallet = Clones.predictDeterministicAddress(TEMPLATE, keccak256(abi.encode(TOKEN, fnftId)));
        wallet = VestedEscrowSmartWallet(smartWallet);
        return (smartWallet, wallet);
    }

```

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +        uint256 fxsFee = (amountToDeposit * MANAGEMENT_FEE) / PRECISION;
This fee calculation is being repeated for both making the deposit and increasing the deposit. Consider moving it to a separate function and reusing in both.
Example:
```solidity
function _claimFees(uint256 amountToLock) private returns (uint256 fxsFee) {
    fxsFee = (amountToLock * MANAGEMENT_FEE) / PRECISION;

    if (fxsFee == 0) {
        return 0;
    }

    IERC20(TOKEN).safeTransferFrom(msg.sender, ADMIN_WALLET, fxsFee);

    emit FeeCollection(address(TOKEN), fxsFee);
}
```

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +    function triggerOutputReceiverUpdate(uint256 fnftId, bytes memory) external override onlyTokenHolder(fnftId) {
This functionality is used multiple times and should be a separate method:
Example
```solidity

    function _claimAllRewards(uint256 fnftId) private {
        (, VestedEscrowSmartWallet wallet) = _getWallets(fnftId);

        for (uint256 i = 0; i <= distributors.length - 1; i++) {
            wallet.claimRewards(msg.sender, ADMIN_WALLET, PERFORMANCE_FEE, distributors[i]);
        }
    }

```

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +        bool hasRewards = (yield > 0) ? true : false;
remove this variable and compare directly in the if condition. We spoke about this ternary operator

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +        return fnftId;
No need to specify return if the parameter is declared within return definition

2024-07-09 12:41 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
> +        require(_msgSender() == VAULT, "E016");
Move this to be a modifier

2024-07-09 12:43 UTC, nikollamalic commented
Generally speaking, when writing Natspec documentation try to use single language explaining what each method does. Imagine as if you are an auditor or a random non-tech enthusiast who wants to understand your code.

2024-07-09 16:00 UTC, thanhtrinh2003 commented on hardhat/foundry.toml
> +mainnet = "https://eth-mainnet.alchemyapi.io/v2/zOVFUzSEld1v_MuTOqGPYkTYttwBUrmF"
oops

2024-07-09 16:33 UTC, nikollamalic commented on hardhat/scripts/foundry/RevestVeFXSDeployment.s.sol
> +    address distritbutor = 0x39333a540bbea6262e405E1A6d435Bd2e776561E;
This one is still using old distributor IRC

2024-07-09 17:32 UTC, thanhtrinh2003 commented on hardhat/contracts/VestedEscrowSmartWallet.sol
> +    function withdraw(uint128 lockId) external onlyMaster {
Done

2024-07-09 17:33 UTC, thanhtrinh2003 commented on hardhat/contracts/VestedEscrowSmartWallet.sol
> +            MAX_INT
Done

2024-07-09 17:47 UTC, thanhtrinh2003 commented on hardhat/contracts/RevestVeFXS.sol
>      address public ADMIN_WALLET;
why, what if we need to migrate ?

2024-07-09 17:56 UTC, thanhtrinh2003 commented on hardhat/contracts/RevestVeFXS.sol
>      constructor(address _provider, address _vE, address _distributor, address _revestAdmin) {
not sure what u meant

2024-07-09 17:57 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
>      address public ADMIN_WALLET;
There is no migration functionality. Either add it or make this role immutable.

2024-07-09 17:59 UTC, nikollamalic commented on hardhat/contracts/RevestVeFXS.sol
>      constructor(address _provider, address _vE, address _distributor, address _revestAdmin) {
Add checks that _provider, _vE, _distributor and _revestAdmin are not zero addresses

2024-07-09 19:58 UTC, nikollamalic commented on hardhat/contracts/VestedEscrowSmartWallet.sol
> +    uint256 private constant MAX_INT = type(uint256).max;
Again, this is not MAX_INT, this is MAX_UINT and there is no need to store this as it can be taken directly from the type

2024-07-09 19:58 UTC, nikollamalic commented on hardhat/contracts/VestedEscrowSmartWallet.sol
> +            MAX_INT
This variable should be removed

2024-07-09 20:00 UTC, thanhtrinh2003 commented on hardhat/contracts/RevestVeFXS.sol
> +    function triggerOutputReceiverUpdate(uint256 fnftId, bytes memory) external override onlyTokenHolder(fnftId) {
bruh this messed the up the msg.sender for rewards in testing, nots ure why, but will checking now

2024-07-10 14:03 UTC, nikollamalic approved these changes
GTG!

2024-07-10 14:03 UTC, merged